name: DeclarativeSwift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Xcode:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xcodebuild -scheme DeclarativeSwift -destination 'platform=iOS Simulator,OS=15.2,name=iPhone 13 Pro'
  CocoaPods:
    name: CocoaPods
    runs-on: macos-latest
    strategy:
      matrix:
        platform: ['ios']
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
    steps:
    - uses: actions/checkout@v1
    - name: CocoaPods ${{ matrix.platform }}
      run: bundle exec pod lib lint --skip-tests --allow-warnings --verbose --platforms=${{ matrix.platform }}
