name: DeclarativeSwift

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  Darwin:
    name: Darwin
    runs-on: macos-latest
    steps:
    - name: Xcode Build
      run: xcodebuild -scheme DeclarativeSwift -destination 'platform=iOS Simulator,OS=15,name=iPhone 11 Pro'
      env:
          SCHEME: DeclarativeSwift
          DESTINATION: platform=iOS Simulator,name=iPhone 13

  CocoaPods:
    name: CocoaPods
    runs-on: macos-latest
    strategy:
      matrix:
        platform: ['ios']
    steps:
    - uses: actions/checkout@v1
    - name: Bundle Install
      run: bundle install
    - name: CocoaPods ${{ matrix.platform }}
      run: bundle exec pod lib lint --skip-tests --allow-warnings --verbose --platforms=${{ matrix.platform }} 
